### ISSUE TITLE
english translation

### ISSUE THREAD

**Issue by fdenzer** [xumingming/pyscheduler#16]
How about an english documentation and in-application texts? Your images look promising.

**Comment by xumingming** [comment]
I am very glad that it looks useful to you :) will take some time to translate the documentation into english

**Comment by xumingming** [comment]
Have write an english readme: https://github.com/xumingming/pyscheduler/blob/master/README_en.md , you can check out the features of this project, but there is still some **Chinese** in the output of this software, if you are still interested with this project after reading the english readme I can take some time to make the software support both English and Chinese.

**Comment by fdenzer** [comment]
Nicely done!
I don't get the table headings, the rest is easily understandable.

I will try do get some attention on on your project,
some students might need vacation or project planing features for their masters degree.

**Comment by xumingming** [comment]
Let me do a translation for you:

**Chinese Version**
```bash
> ./scheduler.py /tmp/test.markdown
任务  | 责任人 | 所需人日 | 开始时间   | 结束时间   | 进度
----- | ------ | -------- | ---------- | ---------- | ----
task1 | James  | 2.0      | 2014-08-21 | 2014-08-22 | 0%
task2 | Lucy   | 1.0      | 2014-08-21 | 2014-08-21 | 0%
task3 | James  | 1.0      | 2014-08-25 | 2014-08-25 | 0%
task4 | Lucy   | 2.0      | 2014-08-22 | 2014-08-25 | 0%
>>> 总人日: 6.0, 已经完成的人日: 0.0, 完成度: 0.00%
```

**Corresponding English Version**
```bash
> ./scheduler.py /tmp/test.markdown
Task  | Developer | Man-Days | Start Date | End Date   | Progress
----- | --------- | -------- | ---------- | ---------- | ----
task1 | James     | 2.0      | 2014-08-21 | 2014-08-22 | 0%
task2 | Lucy      | 1.0      | 2014-08-21 | 2014-08-21 | 0%
task3 | James     | 1.0      | 2014-08-25 | 2014-08-25 | 0%
task4 | Lucy      | 2.0      | 2014-08-22 | 2014-08-25 | 0%
>>> Total Mandays: 6.0, Finished Mandays: 0.0, Total progress: 0.00%
```

**Comment by fdenzer** [comment]
You should probably rerun a modified scheduler to get nice table outputs
for this readme.

**Comment by xumingming** [comment]
Now the scheduler formally support both Chinese and English(with a `-e` option)
